FROM python:3.10.4-bullseye

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY requirements.txt .
RUN pip install --no-binary :all: -r requirements.txt

# Run the application:
COPY myapp.py .
CMD ["python", "myapp.py"]
