FROM python:3.10.4-slim-bullseye

WORKDIR /app

# Copy poetry config
COPY pyproject.toml poetry.lock /app/

# Install poetry, create venv and install our deps
RUN pip install poetry==1.1.13
RUN poetry config virtualenvs.in-project true
RUN poetry install

# Activate venv created by poetry
ENV VIRTUAL_ENV=/app/.venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Run app as regular user
RUN adduser app
USER app

# Our application
COPY myapp.py .
CMD ["python", "myapp.py"]