[tool.poetry]
name = "myapp"
version = "0.1.0"
description = ""
authors = ["Gavrie Philipson"]

[tool.poetry.dependencies]
python = "^3.10"
ujson = "^5.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
